# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/Jhingun1/chingunerdeneochir_T1A3" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "faker", "~> 1.9"